@CBTW.API_HostAddress = http://localhost:5299

## Post to search book info by a prompt
POST {{CBTW.API_HostAddress}}/api/BookInfoSearchBookInfo/
Content-Type: application/json

{
  "text": "Some test text related a book with the author name, title and other info"
}
###
